jaffle_shop:
   target: databricks_job
   outputs:
     databricks_job:
      type: databricks
      method: https
      catalog: toyota_demo
      schema: dbt-jaffle-shop
      host: adb-3025046669923412.12.azuredatabricks.net
      http_path: /sql/1.0/warehouses/900f29f007ac82ce
      token: {{ env_var('DBT_ACCESS_TOKEN') }}